print('Loading npc.lua')

function leo_talk10()
	Talk(1, "Black Market Merchant: Hoho, you must be somebody to locate me. Hoho, what do you need?")
	--Text( 1, "Something special", JumpPage, 2 )
	Text( 1, "Buy.", BuyPage)

	--Talk(2,"Black Market Merchant: Hoho, you are well-informed indeed...How you wish to exchange?")
	--Text(2,"Let me take a look at your things first", SendExchangeData )

	InitExchange()
	DoExchange()

	InitTrade()
	Other(	rand()	)
	Other(	rand()	)
	Other(	rand()	)
	Other(	rand()	)
	Other(	rand()	)
	Other(	rand()	)
	Other(	rand()	)
	Other(	rand()	)

	InitTrigger()
	TriggerAction( 1, AddNpcTrigger, 53, TE_GAMETIME, TT_CYCLETIME, 240, 0 )
	SetNpcTrigger( GetTrigger( 1 ) )
	SetNpcActive()
end

function r_talk57 ()
	InitTrigger()
	TriggerCondition( 1, LvCheck, "<", 6 )
	TriggerCondition( 1, HasRecord, 500 )
	TriggerAction( 1, ReAll )
	TriggerCondition( 2, HasMoney, 200 )
	TriggerAction( 2, TakeMoney, 200 )
	TriggerAction( 2, ReAll )
	TriggerFailure( 2, JumpPage, 2 )

	Talk( 1, "Landy: Hello! I am Nurse Landy of Shaitan City. I just finished my training so How may I assist you?" )
	Text( 1, "Greater Heal", MultiTrigger,GetMultiTrigger(),2)
	--Text( 1, "Record Spawn point", JumpPage, 24 )

	InitTrigger()
	TriggerCondition( 1, LvCheck, "<", 6 )
	TriggerCondition( 1, HasRecord, 500 )
	TriggerAction( 1, ReHp, 50 )
	TriggerCondition( 2, HasMoney, 50 )
	TriggerAction( 2, TakeMoney, 50 )
	TriggerAction( 2, ReHp,50 )
	TriggerFailure( 2, JumpPage, 3 )
	Text( 1, "Heal", MultiTrigger,GetMultiTrigger(),2)
	Talk( 2, "Landy: Sorry, Healing requires 200G. You do not have enough¡­" )
	Talk( 3, "Landy: Sorry! Healing requires 50G¡­You do not have enough¡­" )

	Talk( 24, "Landy: Record spawn right here? Is that correct?" )
	Text( 24, "Yes. Please record.", SetSpawnPos, "Nurse Landy" )
	Text( 24, "No, thank you",CloseTalk )
end

function r_talk76 ()
	InitTrigger()
	TriggerCondition( 1, LvCheck, "<", 6 )
	TriggerCondition( 1, HasRecord, 500 )
	TriggerAction( 1, ReAll )
	TriggerCondition( 2, HasMoney, 200 )
	TriggerAction( 2, TakeMoney, 200 )
	TriggerAction( 2, ReAll )
	TriggerFailure( 2, JumpPage, 2 )

	Talk( 1, "Anne: Hi! I am Nurse Anne. I am finally off probation. Would you like some treatment?" )
	Text( 1, "Greater Heal", MultiTrigger,GetMultiTrigger(),2)

	InitTrigger()
	TriggerCondition( 1, LvCheck, "<", 6 )
	TriggerCondition( 1, HasRecord, 500 )
	TriggerAction( 1, ReHp, 50 )
	TriggerCondition( 2, HasMoney, 50 )
	TriggerAction( 2, TakeMoney, 50 )
	TriggerAction( 2, ReHp,50 )
	TriggerFailure( 2, JumpPage, 3 )
	Text( 1, "Heal", MultiTrigger,GetMultiTrigger(),2)
	Talk( 2, "Anne: Sorry, Healing requires 200G. You do not have enough¡­" )
	Talk( 3, "Anne: Sorry! Healing requires 50G¡­You do not have enough¡­" )

	AddNpcMission	(1018)
	AddNpcMission	(1073)
	AddNpcMission	(1128)
	AddNpcMission	(1181)
	AddNpcMission	(1236)
end 

AddBirthPoint("Chaos Portal", "darkblue", 1363,537)
function x_ChaosHeal ()
	InitTrigger()
	TriggerCondition( 1, LvCheck, "<", 6 )
	TriggerCondition( 1, HasRecord, 500 )
	TriggerAction( 1, ReAll )
	TriggerCondition( 2, HasMoney, 200 )
	TriggerAction( 2, TakeMoney, 200 )
	TriggerAction( 2, ReAll )
	TriggerFailure( 2, JumpPage, 2 )

	Talk( 1, "Tia: Hello, I am Nurse Tia of Chaos Argent. Healings are free of cost until Lv39 and above. 200g for Lv39+!" )
	Text( 1, "Greater Heal", MultiTrigger,GetMultiTrigger(),2)
	Text( 1, "Record Spawn Point", JumpPage, 7 )

	InitTrigger()
	TriggerCondition( 1, LvCheck, "<", 6 )
	TriggerCondition( 1, HasRecord, 500 )
	TriggerAction( 1, ReHp, 50 )
	TriggerCondition( 2, HasMoney, 50 )
	TriggerAction( 2, TakeMoney, 50 )
	TriggerAction( 2, ReHp,50 )
	TriggerFailure( 2, JumpPage, 3 )

	Talk( 2, "Tia: Sorry, healing requires 200G. You do not have enough¡K" )
	Talk( 3, "Tia: Sorry! Healing requires 50G¡KYou do not have enough¡K" )


	Talk( 7, "Tia: Record next to me? Good idea..." )
	Text( 7, "Yes. Please record.", SetSpawnPos, "Chaos Portal")
	Text( 7, "Close",CloseTalk )
end

function BT_NewUser001()
	Talk( 1, "Senna: Hi, I am the image consultant for Argent City. I am responsible for all newcomers and visitors. Look for me if there is something you do not understand." )
	Text( 1, "Star of Unity", JumpPage, 31 )
	Text( 1, "Regarding Argent City", JumpPage, 4 )
	Text( 1, "Regarding Classes and Attributes", JumpPage, 11 )
	Text( 1, "Regarding Monster Coordinates", JumpPage, 30 )
	Text( 1, "I have understood all",  CloseTalk)

	Talk( 4, "Argent City is a place for merchant to sell their products. Have a look around." )
	Text( 4, "Regarding Weapon Shop", JumpPage, 5 )
	Text( 4, "Regarding Armor Shop", JumpPage, 7 )
	Text( 4, "Regarding Item Shop", JumpPage, 8 )
	Text( 4, "Regarding Teleporter", JumpPage, 9 )
	Text( 4, "Regarding the Nurse", JumpPage, 10 )

	Talk( 5, "Argent City's Blacksmith Goldie deals in the sale of weapons. His weapons are of excellent quality. Go take a look. Blacksmith's shop is at Argent City's top left corner." )
	Text( 5, "Regarding other shops", JumpPage, 4 )
	Text( 5, "I have understood all",  CloseTalk )

--	Talk( 6, "Look for me again if there is anything you don't understand", CloseTalk )

	Talk( 7, "Armors made in Argent City are very durable. You can have a look at them at the top right corner of the city." )
	Text( 7, "Regarding other shops", JumpPage, 4 )
	Text( 7, "I have understood all",  CloseTalk )

	Talk( 8, "We have a lot of items here that are important to an Explorer. Check it out on the right side of the pond." )
	Text( 8, "Regarding other shops", JumpPage, 4 )
	Text( 8, "I have understood all",  CloseTalk )

	Talk( 9, "Teleporter can send you to any city in this land. They can also record the spawn point for you. She is beside the western gate." )
	Text( 9, "Regarding other shops", JumpPage, 4 )
	Text( 9, "I have understood all",  CloseTalk )

	Talk( 10, "The nurse is just slightly below the fountain. She is a gentle and caring lady that is well loved by all." )
	Text( 10, "Regarding other shops", JumpPage, 4 )
	Text( 10, "I have understood all", CloseTalk)

	
	InitTrigger()
	TriggerCondition( 1, NoRecord, 700 )
	TriggerCondition( 1, HasMission, 700 )
	TriggerCondition( 1, NoFlag, 700, 10 )
	TriggerAction( 1, SetFlag, 700, 10)
	TriggerAction( 1, JumpPage, 12 )
	TriggerFailure( 1, JumpPage, 12 )
	Talk( 11, "Senna: Being a new player, you must understand the basic of each class and attributes. What you wish to know?" )
	Text( 11, "Regarding Classes", JumpPage, 12)
	Text( 11, "Regarding Attributes", JumpPage, 13)
	Text( 11, "I have understood all", JumpPage, 6 )
	--Text( 11, "Regarding Classes", MultiTrigger, GetMultiTrigger(), 1)

	InitTrigger()
	TriggerCondition( 1, NoRecord, 700 )
	TriggerCondition( 1, HasMission, 700 )
	TriggerCondition( 1, NoFlag, 700, 20 )
	TriggerAction( 1, SetFlag, 700, 20)
	TriggerAction( 1, JumpPage, 13 )
	TriggerFailure( 1, JumpPage, 13 )
	--Text( 11, "Regarding Attributes", MultiTrigger, GetMultiTrigger(), 1)

	Talk( 12, "Senna: There are 7 basic classes in this game. Each has its unique ways and serves a special purpose in the game. Which would you like to become?" )
	Text( 12, "Regarding Swordsman", JumpPage, 14 )
	Text( 12, "Regarding Hunter", JumpPage, 15 )
--	Text( 12, "Regarding Sailor", JumpPage, 16 )
	Text( 12, "Regarding Explorer", JumpPage, 17 )
	Text( 12, "Regarding Herbalist", JumpPage, 18 )
--	Text( 12, "Regarding Artisan", JumpPage, 19 )
--	Text( 12, "Regarding Merchant", JumpPage, 20 )
	Text( 12, "Understood. Let me check out others.", JumpPage, 11 )

	Talk( 13, "Senna: Each character will have 5 base attributes. Players can increase them accordingly to raise certain aspect of their ability. Each level will reward players with 1 stat point and 1 skill point. Beginner will have 5 stat points to distribute." )
	Text( 13, "Regarding Strength", JumpPage, 21 )
	Text( 13, "Regarding Agility", JumpPage, 22 )
	Text( 13, "Regarding Constitution", JumpPage, 23 )
	Text( 13, "Regarding Spirit", JumpPage, 24 )
	--Text( 13, "Regarding Luck", JumpPage, 25 )
	Text( 13, "Regarding Accuracy", JumpPage, 26 )
	Text( 13, "Understood. Let me check out others.", JumpPage, 11 )

	Talk( 14, "Senna: Swordsman has the highest physical resistance in this game. Male character may choose to become one when they reach Lv 10. Look for Peter in Argent City to select the Swordsman class." )
	Text( 14, "Regarding other Classes", JumpPage, 12)
	Text( 14, "Regarding Attributes", JumpPage, 13)
	Text( 14, "I have understood all", JumpPage, 27)

	Talk( 15, "Senna: Hunters is the only long range class in this game. After further advancement, they can learn to use fireguns which have higher damage. Only Lance and Phyllis may become a Hunter. Players Lv 10 and above can look for Ray in Icicle to become a Hunter." )
	Text( 15, "Regarding other Classes", JumpPage, 12)
	Text( 15, "Regarding Attributes", JumpPage, 13)
	Text( 15, "I have understood all", JumpPage, 27)

	Talk( 16, "Senna: Sailor is the strongest class in the sea. It is still unreleased in current version." )
	Text( 16, "Regarding other Classes", JumpPage, 12)
	Text( 16, "Regarding Attributes", JumpPage, 13)
	Text( 16, "I have understood all", JumpPage, 27)
	
	Talk( 17, "Senna: Senna: Explorer are the best support class in the sea. Beside Carsise, all other 3 character can apply for this class. Players Lv 10 and above can talk to Little Daniel in Argent City to become an Explorer." )
	Text( 17, "Regarding other Classes", JumpPage, 12)
	Text( 17, "Regarding Attributes", JumpPage, 13)
	Text( 17, "I have understood all", JumpPage, 27)

	Talk( 18, "Resline: Herbalist are loyal followers of Goddess Kara. They possess mystical healing ability. Only Phyllis and Ami can select to become a Herbalist. Lv 10 players can look for High Priest - Gannon in Shaitan City to become a Herbalist." )
	Text( 18, "Regarding other Classes", JumpPage, 12)
	Text( 18, "Regarding Attributes", JumpPage, 13)
	Text( 18, "I have understood all", JumpPage, 27)

	Talk( 19, "Senna: Artisan is the only class that can make item. They will be in-charge of building structures for the guild. It is still unreleased in current version." )
	Text( 19, "Regarding other Classes", JumpPage, 12)
	Text( 19, "Regarding Attributes", JumpPage, 13)
	Text( 19, "I have understood all", JumpPage, 27)

	Talk( 20, "Senna: Merchant is the richest of all classes as they specialise in commerce. It is still unreleased in current version." )
	Text( 20, "Regarding other Classes", JumpPage, 12)
	Text( 20, "Regarding Attributes", JumpPage, 13)
	Text( 20, "I have understood all", JumpPage, 27)

	Talk( 21, "Senna: Strength increases Melee Attack power" )
	Text( 21, "Enquire about other Attributes", JumpPage, 13)
	Text( 21, "Enquire about other Classes", JumpPage, 12)
	Text( 21, "I have understood all", JumpPage, 27)

	Talk( 22, "Senna: Agility increases Attack Speed and Dodge Rate" )
	Text( 22, "Enquire about other Attributes", JumpPage, 13)
	Text( 22, "Enquire about other Classes", JumpPage, 12)
	Text( 22, "I have understood all", JumpPage, 27)

	Talk( 23, "Senna: Constitution increases Max HP and Physical Resist" )
	Text( 23, "Enquire about other Attributes", JumpPage, 13)
	Text( 23, "Enquire about other Classes", JumpPage, 12)
	Text( 23, "I have understood all", JumpPage, 27)

	Talk( 24, "Senna: Spirit increases Max SP and certain skill effect" )
	Text( 24, "Enquire about other Attributes", JumpPage, 13)
	Text( 24, "Enquire about other Classes", JumpPage, 12)
	Text( 24, "I have understood all", JumpPage, 27)

	Talk( 25, "Senna: Luck increases Critical Rate and Combining Rate" )
	Text( 25, "Enquire about other Attributes", JumpPage, 13)
	Text( 25, "Enquire about other Classes", JumpPage, 12)
	Text( 25, "I have understood all", JumpPage, 27)

	Talk( 26, "Senna: Accuracy increases Hit Rate and Range Attack power" )
	Text( 26, "Enquire about other Attributes", JumpPage, 13)
	Text( 26, "Enquire about other Classes", JumpPage, 12)
	Text( 26, "I have understood all", JumpPage, 27)

	Talk( 27, "Senna: Ok, look for me again if you have something that you do not understand.")
	
	Talk( 28, "Well done, it looks like you now have a good grasp at basic combat and also a good idea on how item drops work. Since there is nothing much left to learn from me, why don't you go and look for my friends? If fighting is your cup of tea, seek out Marcusa. He's a patroller and is often seen patrolling about the outskirts of this city. He was last seen at (2085, 2742). Another person you may like to meet would be Ditto (2250, 2770), Argent City's famous physician. Lately, he has been looking for helpers to help him collect more ingredients for his medicine. If you are interested, you can look for him on the right side of the city fountain (2250, 2770)." )
	Text( 28, "Regarding Argent City", JumpPage, 4 )
	Text( 28, "Regarding Classes and Attributes", JumpPage, 11 )
	Text( 28, "I have understood all",  CloseTalk)

	Talk( 29, "Senna: Very well! You have progressed to Lv 9. You can choose your class at Lv 10. Go now to the related NPC to start your trial for the class you wish to become. Swordsman look for Peter in Argent City at (2192, 2767). Herbalist look for High Priest - Gannon in Shaitan City at (862, 3500). Hunter look for Swordsman - Ray in Icicle Castle at (1365, 570). Explorer look for Little Daniel at (2193, 2730). You can reach Argent or Shaitan by using the teleporter." )
	Text( 29, "I would like to ask about something", JumpPage, 4 )
	Text( 29, "Regarding Classes and Attributes", JumpPage, 11 )
	Text( 29, "I have understood all",  CloseTalk )

	Talk( 30, "Senna: To check the coordinates of monsters in game, all you have to do is look for a Drunkyard in Argent City Bar at (2222, 288). He can tell you the coordinates for a fee." )
	
	--[[InitTrigger()
	-- added by kong@pkodev.net (12.06.17) begin
	TriggerCondition( 1, KitbagLock, 0 )
	TriggerCondition( 1, HasLeaveBagGrid, 1 )
	-- end
	TriggerCondition( 1, NoItem, 1034, 1 )
	TriggerCondition( 1, NoItem, 1033, 1 )
	TriggerCondition( 1, BankNoItem, 1034, 1 )
	TriggerCondition( 1, BankNoItem, 1033, 1 )
	TriggerCondition( 1, EquipNoItem, 1034, 1 )
	TriggerCondition( 1, EquipNoItem, 1033, 1 )

	TriggerCondition( 1, LvCheck, "<", 41 )
	TriggerAction( 1, GiveItem, 1033, 1, 4 )
	TriggerFailure( 1, JumpPage, 6 )
	Talk( 31, "Senna: Star of Unity is a mysterious accessory from another world. When you equip it, you might be able to activate the power of unity and something unexpected might happen. We are running a trial event 'Hoard Exchange'. All players below Lv 41 can redeem a Star of Unity to exchange for a suitable piece of equipment. Are you interested?" )
	Text( 31, "Redeem Star of Unity",MultiTrigger, GetMultiTrigger(), 1)
	Text( 31, "Hoard Exchange",JumpPage, 32 )]]

	Talk( 31, "Senna: Star of Unity is a mysterious accessory from another world. When you equip it something unexpected might happen. Once the energy of the Star of Unity has been fulfilled, you may redeem for a lv50 class weapon." )
	Text( 31, "Redeem class weapon", Transfer_TeamStar, 1)
	Talk( 6, "Senna: I'm sorry, you are not qualified to receive the prize." )

	AddNpcMission ( 701 )
	AddNpcMission ( 702 )
	AddNpcMission ( 704 )
	AddNpcMission ( 706 )
	AddNpcMission ( 708 )
	AddNpcMission ( 200 )
	AddNpcMission 	(402)
	AddNpcMission 	(50)
	AddNpcMission 	(51)
	AddNpcMission 	(61)
	AddNpcMission 	(62)
	AddNpcMission 	(63)
	AddNpcMission 	(64)
	AddNpcMission 	(65)
	AddNpcMission 	(82)

	MisListPage(28)
	MisListPage(29)
end

r_talk13 = nil
function r_talk13 ()
	Talk( 1, "Monica: Hi, I am Banker Monica. Accounts can never go wrong with me around." )
	--InitTrigger()
	--TriggerCondition( 1, HasMoney, 200 )
	--TriggerAction( 1, TakeMoney, 200 )
	--TriggerAction( 1, OpenBank )
	--TriggerFailure( 1, JumpPage, 2 )
	--Text( 1, "Vault (200G Fee)", MultiTrigger, GetMultiTrigger(), 1)
	Text( 1, "Vault (PIN)", RequestClientPin, enumPinForBank)

	--[[InitTrigger()
	TriggerCondition( 1, HasMoney, 5000 )
	TriggerAction( 1, TakeMoney, 5000 )
	TriggerAction( 1, OpenGuildBank )
	TriggerFailure( 1, JumpPage, 2 )
	Text( 1, "Guild Bank (50,000G Fee)", MultiTrigger, GetMultiTrigger(), 1)]]

	--Talk( 2, "Sorry, you do not have sufficient gold to pay for vault usage" )

	AddNpcMission(1050)
	AddNpcMission(1212)
	AddNpcMission(6091)
	AddNpcMission(6092)
end

r_talk234 = nil
function r_talk234()
	Talk( 1, "Cartel: Hi! Want a change of hairstyle? Be hip and keep up with the trend!" )
	Text( 1, "I want to change my hairstyle", OpenHair )
	Text( 1, "Forget it", CloseTalk )
end

r_talk07 = nil
function r_talk07 ()
	Talk( 1, "Jimberry: Hi, welcome! How can I help you?" )
	Text( 1, "Trade", BuyPage )
	Text( 1, "Redeem Reality Mask",JumpPage, 2 )
	Text( 1, "Nothing...",CloseTalk )

	InitTrade()
	Other(	3297	)
	Other(	3298	)
	Other(	3164	)
	Other(	3160	)
	Other(	3161	)
	Other(	3165	)
	Other(	3238	)
	Other(	3170	)
	Other(	3293	)
	Other(	3174	)
	Other(	3163	)
	Other(	3176	)
	Other(	3180	)
	Other(	3179	)
	Other(	3177	)
	Other(	3168	)
	Other(	3162	)
	Other(	3166	)
	Other(	3167	)
	Other(	3172	)
	Other(	3173	)
	Other(	3227	)
	Other(	3231	)
	Other(	3228	)
	Other(	3229	)
	Other(	3230	)
	Other(	3232	)
	Other(	3233	)
	Other(	3234	)
	Other(	3235	)
	Other(	3236	)
	Other(	3237	)
	Other(	3225	)
	Other(	3226	)
	Other(	3294	)
	Other(	3295	)
	Other(	3141	)
	Other(	4602	)
	Other(	4603	)
	Other(	4604	)
	Other(	3296	)
	Other(	3299	)
	Other(	2679	)
	Other(	2689	)
	Other(	2699	)
	Other(	2709	)
	Other(	1611	)
	Other(	1682	)
	Other(	1842	)
	Other(	1612	)
	Other(	1710	)
	Other(	1693	)
	Other(	4716	)
	Other(	1716	)
	Other(	1711	)
	Other(	3384	)
	Other(	3932	)
	Other(	1619	)
	Other(	2396	)
	Other(	1729	)
	Other(	4459	)
	Other(	1697	)
	Other(	1730	)
	Other(	1712	)
	Other(	1734	)
	Other(	1621	)
	Other(	1703	)
	--Other(	3288	)
	Other(	2440	)
	Other(	9500	)

	InitTrigger()
	TriggerCondition( 1, HasLeaveBagGrid, 1 )
	TriggerCondition( 1, KitbagLock, 0 )
	TriggerCondition( 1, HasItem, 2588, 1 )
	TriggerCondition( 1, HasItem, 1624, 10 )
	TriggerCondition( 1, HasMoney, 10000 )
	TriggerAction( 1, TakeItem, 2588, 1 )
	TriggerAction( 1, TakeItem, 1624, 10 )
	TriggerAction( 1, TakeMoney, 10000 )
	TriggerAction( 1, GiveItem, 2326, 1 , 4)
	TriggerAction( 1, JumpPage, 3 )
	TriggerFailure( 1, JumpPage, 4 )
	Talk( 2, "To obtain a Reality Mask requires 1 Elven Signet, 10000G and any of 10x Lv3 gathered resource" )
	Text( 2, "Bones to change a Reality Mask", MultiTrigger, GetMultiTrigger(), 1)

	InitTrigger()
	TriggerCondition( 1, HasLeaveBagGrid, 1 )
	TriggerCondition( 1, KitbagLock, 0 )
	TriggerCondition( 1, HasItem, 2588, 1 )
	TriggerCondition( 1, HasItem, 4031, 10 )
	TriggerCondition( 1, HasMoney, 10000 )
	TriggerAction( 1, TakeItem, 2588, 1 )
	TriggerAction( 1, TakeItem, 4031, 10 )
	TriggerAction( 1, TakeMoney, 10000 )
	TriggerAction( 1, GiveItem, 2326, 1 , 4)
	TriggerAction( 1, JumpPage, 3 )
	TriggerFailure( 1, JumpPage, 4 )
	Text( 2, "Crystal Eolith to change a Reality Mask", MultiTrigger, GetMultiTrigger(), 1)

	InitTrigger()
	TriggerCondition( 1, HasLeaveBagGrid, 1 )
	TriggerCondition( 1, KitbagLock, 0 )
	TriggerCondition( 1, HasItem, 2588, 1 )
	TriggerCondition( 1, HasItem, 3991, 10 )
	TriggerCondition( 1, HasMoney, 10000 )
	TriggerAction( 1, TakeItem, 2588, 1 )
	TriggerAction( 1, TakeItem, 3991, 10 )
	TriggerAction( 1, TakeMoney, 10000 )
	TriggerAction( 1, GiveItem, 2326, 1 , 4)
	TriggerAction( 1, JumpPage, 3 )
	TriggerFailure( 1, JumpPage, 4 )
	Text( 2, "Teak Wood Log to change a Reality Mask ", MultiTrigger, GetMultiTrigger(), 1)

	InitTrigger()
	TriggerCondition( 1, HasLeaveBagGrid, 1 )
	TriggerCondition( 1, KitbagLock, 0 )
	TriggerCondition( 1, HasItem, 2588, 1 )
	TriggerCondition( 1, HasItem, 4011, 10 )
	TriggerCondition( 1, HasMoney, 10000 )
	TriggerAction( 1, TakeItem, 2588, 1 )
	TriggerAction( 1, TakeItem, 4011, 10 )
	TriggerAction( 1, TakeMoney, 50000 )
	TriggerAction( 1, GiveItem, 2326, 1 , 4)
	TriggerAction( 1, JumpPage, 3 )
	TriggerFailure( 1, JumpPage, 4 )
	Text( 2, "Bubble Fish to change a Reality Mask", MultiTrigger, GetMultiTrigger(), 1)

	Talk( 3, "Jimberry: Keep it well, this is important!" )
	Talk( 4, "Jimberry: You do not seem to have enough materials. Your inventory may be binded or you do not have enough free slots." )
end

r_talk242 = nil
function r_talk242()

	Talk( 14, "Bingo: Give me a Christmas Gem Voucher, and you will get a high quality gem." )
	InitTrigger() --¸ß¼¶±¦Ê¯¶Ò»»È¯
	TriggerCondition( 1, HasItem,2899, 1 )
	TriggerCondition( 1, HasLeaveBagGrid, 3 )
	TriggerCondition( 1, KitbagLock, 0 )
	TriggerAction( 1, TakeItem, 2899, 1 )
	TriggerAction( 1, GiveItem, 0860, 3, 101 )
	TriggerFailure( 1, JumpPage, 15 )
	Text( 14, "Exchanged 3 Gem of the Wind.",MultiTrigger, GetMultiTrigger(), 1) 
	InitTrigger() --¸ß¼¶±¦Ê¯¶Ò»»È¯
	TriggerCondition( 1, HasItem,2899, 1 )
	TriggerCondition( 1, HasLeaveBagGrid, 3 )
	TriggerCondition( 1, KitbagLock, 0 )
	TriggerAction( 1, TakeItem, 2899, 1 )
	TriggerAction( 1, GiveItem, 0861, 3,101 )
	TriggerFailure( 1, JumpPage, 15 )
	Text( 14, "Redeem 3 Gem of Striking",MultiTrigger, GetMultiTrigger(), 1) 

	InitTrigger() --¸ß¼¶±¦Ê¯¶Ò»»È¯
	TriggerCondition( 1, HasItem,2899, 1 )
	TriggerCondition( 1, HasLeaveBagGrid, 3 )
	TriggerCondition( 1, KitbagLock, 0 )
	TriggerAction( 1, TakeItem, 2899, 1 )
	TriggerAction( 1, GiveItem, 0862, 3,101 )
	TriggerFailure( 1, JumpPage, 15 )
	Text( 14, "Exchanged 3 Gem of Colossus",MultiTrigger, GetMultiTrigger(), 1) 

	InitTrigger() --¸ß¼¶±¦Ê¯¶Ò»»È¯
	TriggerCondition( 1, HasItem,2899, 1 )
	TriggerCondition( 1, HasLeaveBagGrid, 3 )
	TriggerCondition( 1, KitbagLock, 0 )
	TriggerAction( 1, TakeItem, 2899, 1 )
	TriggerAction( 1, GiveItem, 0863, 3,101 )
	TriggerFailure( 1, JumpPage, 15 )
	Text( 14, "Exchanged 3 Gem of Rage",MultiTrigger, GetMultiTrigger(), 1) 
	InitTrigger() --¸ß¼¶±¦Ê¯¶Ò»»È¯
	TriggerCondition( 1, HasItem,2899, 1 )
	TriggerCondition( 1, HasLeaveBagGrid, 1 )
	TriggerCondition( 1, KitbagLock, 0 )
	TriggerAction( 1, TakeItem, 2899, 1 )
	TriggerAction( 1, GiveItem, 1012, 1,101 )
	TriggerFailure( 1, JumpPage, 15 )
	Text( 14, "Redeem 1 Gem of Soul",MultiTrigger, GetMultiTrigger(), 1) 

	Talk( 15, "Redemption failed. You do not seem to have any Christmas Gem Voucher or your inventory has been binded. " )
	Talk( 16, "Merry Christmas!" )

	Talk( 1, "Bingo: I have the latest news around here and it is reliable.")
	--Text( 1, "Christmas Gem Voucher", JumpPage, 14 )
	Text( 1, "Unique Gem Voucher", JumpPage, 12 )
	Text( 1, "Lv 1 Refining Gem Voucher", JumpPage, 2 )
	Text( 1, "Lv 2 Refining Gem Voucher", JumpPage, 3 )
	Text( 1, "Refining Gem Voucher", JumpPage, 4 )
	Text( 1, "Combine Wishing Stone", JumpPage, 6 )
	Text( 1, "Gem Voucher", JumpPage, 5 )

	Talk( 2, "Bingo: Pass me one Lv 1 Refining Gem Voucher to exchange for a Lv 1 Refining Gem. Also, you might obtain an additional random Lv1 Attribute Gem.")
	Text( 2, "Confirm to redeem", TransferDiamond, 1)

	Talk( 3, "Bingo: Bring me a Lv 2 Refining Gem Voucher to exchange for a Lv 2 Refining Gem. You might also obtain an additional random Lv 2 Attribute Gem.")
	Text( 3, "Confirm to redeem", TransferDiamond, 2)

	Talk( 4, "Bingo: Pass me one Refining Gem Voucher to exchange for a Lv 1 Refining Gem")
	Text( 4, "Confirm to redeem", TransferDiamond, 3)

	Talk( 5, "Bingo: Bring me a Gem Voucher in exchange for a Lv 1 Gem.")
	Text( 5, "Confirm to redeem", TransferDiamond, 4)

	Talk( 17, "Bingo: Do you have Pirate Vouchers?")

	InitTrigger()--¶Ò»»"IPOD"¶Ò»»È¯
	TriggerCondition( 1, HasItem, 2238, 1 )
	TriggerCondition( 1, HasLeaveBagGrid, 1 )
	TriggerCondition( 1, KitbagLock, 0 )
	TriggerAction( 1, TakeItem, 2238, 1 )
 	TriggerAction( 1, GiveItem, 2306, 1 ,4)
	TriggerFailure( 1, JumpPage, 18 )
	Text( 17, "I have Pirate Voucher 8",MultiTrigger, GetMultiTrigger(), 1)

	Text( 17, "I have Pirate Voucher 6",JumpPage, 19)
	Talk(19,"Do you wish to exchange?")
	Text( 19, "Confirm to exchange",GetChaName_5, 1)

	InitTrigger()--¶Ò»»¾«ÁéÓ²±Ò99¸ö
	TriggerCondition( 1, HasItem, 2237, 1 )
	TriggerCondition( 1, HasLeaveBagGrid, 1 )
	TriggerCondition( 1, KitbagLock, 0 )
	TriggerAction( 1, TakeItem, 2237, 1 )
 	TriggerAction( 1, GiveItem, 855, 99 ,4)
	TriggerFailure( 1, JumpPage, 18 )
	Text( 17, "I have Pirate Voucher 9",MultiTrigger, GetMultiTrigger(), 1)

	InitTrigger()-- ¶Ò»»ÖýÔìÍ¼Ö½"Encrypted Blueprint"£±ÕÅ
	TriggerCondition( 1, HasItem, 2239, 1 )
	TriggerCondition( 1, HasLeaveBagGrid, 1 )
	TriggerCondition( 1, KitbagLock, 0 )
	TriggerAction( 1, TakeItem, 2239, 1 )
 	TriggerAction( 1, GiveItem, 1001, 1 ,4)
	TriggerFailure( 1, JumpPage, 18 )
	Text( 17, "I have Pirate Voucher 7",MultiTrigger, GetMultiTrigger(), 1)

	InitTrigger()--¶Ò»»¼ÓËÙ³É³¤¹û1¸ö
	TriggerCondition( 1, HasItem, 2241, 1 )
	TriggerCondition( 1, HasLeaveBagGrid, 1 )
	TriggerCondition( 1, KitbagLock, 0 )
	TriggerAction( 1, TakeItem, 2241, 1 )
 	TriggerAction( 1, GiveItem, 0578, 1 ,4)
	TriggerFailure( 1, JumpPage, 18 )
	Text( 17, "I have Pirate Voucher 5",MultiTrigger, GetMultiTrigger(), 1)
	Text( 17, "Total amount of other Pirate Voucher", GetChaName_4, 1)

	Talk( 18, "Bingo: You do not seem to have the suitable Pirate Voucher. Please check to see if your inventory is binded and that theres a least 1 empty slot.")

 	InitTrigger() --ºÏ³ÉÐíÔ¸Ê¯
	TriggerCondition( 1, HasItem, 3905, 5 )
	TriggerCondition( 1, HasItem, 3907, 1 )
	TriggerCondition( 1, HasLeaveBagGrid, 1 )
	TriggerCondition( 1, KitbagLock, 0 )
	TriggerAction( 1, TakeItem, 3905, 5 )
	TriggerAction( 1, TakeItem, 3907, 1 )
 	TriggerAction( 1, GiveItem, 3906, 1 ,4)
	TriggerFailure( 1, JumpPage, 8 )
	Talk( 6, "Bingo: Bring me 5 Dark Wishing Stone and 1 Welding Catalyst, I will make 1 Sparkling Wishing Stone for you.")
	Text( 6, "Confirm to combine",MultiTrigger, GetMultiTrigger(), 1)        

	Talk( 8, "Bingo: You seems to lack Wishing Stones and Welding Catalyst! Please make sure that your inventory is not binded and has at least 1 empty slot.")

	InitTrigger() --¶Ò»»ÈýÔÂ¾«Áé
	TriggerCondition( 1, HasItem, 3342, 2 )
	TriggerCondition( 1, HasItem, 3337, 1 )
	TriggerCondition( 1, HasLeaveBagGrid, 1 )
	TriggerCondition( 1, KitbagLock, 0 )
	TriggerAction( 1, TakeItem, 3342, 2 )
	TriggerAction( 1, TakeItem, 3337, 1 )
	TriggerAction( 1, GiveItem, 3335, 1 ,4)
	TriggerFailure( 1, JumpPage, 11 ) 
	Talk( 10, "Bingo: Bring me 2 Lantern and 1 Fairy Soul to exchange for a Fairy March. Question regarding Fairy Soul? Go to 'Hafta Haven' and look for 'Harbor Operator - Whitcombe'.")
	Text( 10, "Confirm trade",MultiTrigger, GetMultiTrigger(), 1) 

	Talk( 11, "Bingo: Fairy March requires 2 Lanterns and 1 Fairy Soul. Please make sure that your inventory is not binded and has at least 1 empty inventory slot.")

	Talk( 12, "Bingo: Give me 1 Unique Gem Voucher to exchange for x1 of the following five gems.")

	InitTrigger() --¸ß¼¶±¦Ê¯¶Ò»»È¯
	TriggerCondition( 1, HasItem, 0333, 1 )
	TriggerCondition( 1, HasLeaveBagGrid, 1 )
	TriggerCondition( 1, KitbagLock, 0 )
	TriggerAction( 1, TakeItem, 0333, 1 )
	TriggerAction( 1, GiveItem, 0863, 1,101 )
	TriggerFailure( 1, JumpPage, 13 ) 
	Text( 12, "Gem of Rage",MultiTrigger, GetMultiTrigger(), 1) 

	InitTrigger() --¸ß¼¶±¦Ê¯¶Ò»»È¯
	TriggerCondition( 1, HasItem, 0333, 1 )
	TriggerCondition( 1, HasLeaveBagGrid, 1 )
	TriggerCondition( 1, KitbagLock, 0 )
	TriggerAction( 1, TakeItem, 0333, 1 )
	TriggerAction( 1, GiveItem, 0860, 1, 101 )
	TriggerFailure( 1, JumpPage, 13 ) 
	Text( 12, "Gem of the Wind",MultiTrigger, GetMultiTrigger(), 1) 

	InitTrigger() --¸ß¼¶±¦Ê¯¶Ò»»È¯
	TriggerCondition( 1, HasItem, 0333, 1 )
	TriggerCondition( 1, HasLeaveBagGrid, 1)
	TriggerCondition( 1, KitbagLock, 0 )
	TriggerAction( 1, TakeItem, 0333, 1 )
	TriggerAction( 1, GiveItem, 0861, 1,101 )
	TriggerFailure( 1, JumpPage, 13 ) 
	Text( 12, "Gem of Striking",MultiTrigger, GetMultiTrigger(), 1) 

	InitTrigger() --¸ß¼¶±¦Ê¯¶Ò»»È¯
	TriggerCondition( 1, HasItem, 0333, 1 )
	TriggerCondition( 1, HasLeaveBagGrid,1 )
	TriggerCondition( 1, KitbagLock, 0 )
	TriggerAction( 1, TakeItem, 0333, 1 )
	TriggerAction( 1, GiveItem, 0862, 1,101 )
	TriggerFailure( 1, JumpPage, 13 ) 
	Text( 12, "Gem of Colossus",MultiTrigger, GetMultiTrigger(), 1) 

	InitTrigger() --¸ß¼¶±¦Ê¯¶Ò»»È¯
	TriggerCondition( 1, HasItem, 0333, 1 )
	TriggerCondition( 1, HasLeaveBagGrid,1 )
	TriggerCondition( 1, KitbagLock, 0 )
	TriggerAction( 1, TakeItem, 0333, 1 )
	TriggerAction( 1, GiveItem, 1012, 1,101 )
	TriggerFailure( 1, JumpPage, 13 ) 
	Text( 12, "Gem of Soul",MultiTrigger, GetMultiTrigger(), 1) 

	Talk( 13, "Bingo: You do not seem to have any Unique Gem Voucher. Please make sure that your inventory is not binded and has at least 1 empty inventory slots.")
	Talk( 20, "Bingo: Do you have many moon cakes? You can exchange much great stuff from me." )
	InitTrigger() --99¸ö£ºÃÔÖ®Ëø10¸ö
	TriggerCondition( 1, HasItem,3915, 99 )
	TriggerCondition( 1, HasLeaveBagGrid, 1 )
	TriggerCondition( 1, KitbagLock, 0 )
	TriggerAction( 1, TakeItem, 3915, 99 )
	TriggerAction( 1, GiveItem, 2440, 10, 4 )
	TriggerFailure( 1, JumpPage, 21 )
	Text( 20, "Exchange 10 Locks of Mystic",MultiTrigger, GetMultiTrigger(), 1) 
	
	InitTrigger() --100¸ö£º²Æ¸»1¸ö
	TriggerCondition( 1, HasItem,3915, 100 )
	TriggerCondition( 1, HasLeaveBagGrid, 1 )
	TriggerCondition( 1, KitbagLock, 0 )
	TriggerAction( 1, TakeItem, 3915, 100 )
	TriggerAction( 1, GiveItem, 3096, 1,4 )
	TriggerFailure( 1, JumpPage, 21 )
	Text( 20, "Exchange one Amplifier of Luck",MultiTrigger, GetMultiTrigger(), 1) 

	InitTrigger() --200¸ö£º²Ø±¦Í¼1¸ö
	TriggerCondition( 1, HasItem,3915, 200 )
	TriggerCondition( 1, HasLeaveBagGrid, 1 )
	TriggerCondition( 1, KitbagLock, 0 )
	TriggerAction( 1, TakeItem, 3915, 200 )
	TriggerAction( 1, GiveItem, 1092, 1,4 )
	TriggerFailure( 1, JumpPage, 21 )
	Text( 20, "Exchange one Treasure Map",MultiTrigger, GetMultiTrigger(), 1) 

	InitTrigger() --300¸ö£º99°ü1¸ö
	TriggerCondition( 1, HasItem,3915, 300 )
	TriggerCondition( 1, HasLeaveBagGrid, 1 )
	TriggerCondition( 1, KitbagLock, 0 )
	TriggerAction( 1, TakeItem, 3915, 300 )
	TriggerAction( 1, GiveItem, 1095, 1,4 )
	TriggerFailure( 1, JumpPage, 21 )
	Text( 20, "Exchange one 99 Parcel",MultiTrigger, GetMultiTrigger(), 1) 
	
	InitTrigger() --2000¸ö£º¼ÓÄÉÖ®Éñ£¨¾«Éñ¼Ó5£©
	TriggerCondition( 1, HasItem,3915, 2000 )
	TriggerCondition( 1, HasLeaveBagGrid, 1 )
	TriggerCondition( 1, KitbagLock, 0 )
	TriggerAction( 1, TakeItem, 3915, 2000 )
	TriggerAction( 1, GiveItem, 1012, 1,4 )
	TriggerFailure( 1, JumpPage, 21 )
	Text( 20, "Exchange one Gem of Soul",MultiTrigger, GetMultiTrigger(), 1) 
	Text( 20, "Next page", JumpPage, 22 )

	Talk( 22, "Bingo: Do you have many moon cakes? You can exchange much great stuff from me." )

	InitTrigger() --2000¸ö£ºÑ×Óñ£¨Á¦Á¿¼Ó5£©
	TriggerCondition( 1, HasItem,3915, 2000 )
	TriggerCondition( 1, HasLeaveBagGrid, 1 )
	TriggerCondition( 1, KitbagLock, 0 )
	TriggerAction( 1, TakeItem, 3915, 2000 )
	TriggerAction( 1, GiveItem, 863, 1,4 )
	TriggerFailure( 1, JumpPage, 21 )
	Text( 22, "Exchange one Gem of Rage",MultiTrigger, GetMultiTrigger(), 1) 

	InitTrigger() --2000¸ö£ºÑÒÓñ£¨ÌåÖÊ¼Ó5£©
	TriggerCondition( 1, HasItem,3915, 2000 )
	TriggerCondition( 1, HasLeaveBagGrid, 1 )
	TriggerCondition( 1, KitbagLock, 0 )
	TriggerAction( 1, TakeItem, 3915, 2000 )
	TriggerAction( 1, GiveItem, 862, 1,4 )
	TriggerFailure( 1, JumpPage, 21 )
	Text( 22, "Exchange one Gem of Colossus",MultiTrigger, GetMultiTrigger(), 1) 

	InitTrigger() --2000¸ö£ºÓ¥ÑÛÊ¯£¨×¨×¢¼Ó5£©
	TriggerCondition( 1, HasItem,3915, 2000 )
	TriggerCondition( 1, HasLeaveBagGrid, 1 )
	TriggerCondition( 1, KitbagLock, 0 )
	TriggerAction( 1, TakeItem, 3915, 2000 )
	TriggerAction( 1, GiveItem, 861, 1,4 )
	TriggerFailure( 1, JumpPage, 21 )
	Text( 22, "Exchange one Gem of Striking",MultiTrigger, GetMultiTrigger(), 1) 

	InitTrigger() --2000¸ö£º·çÁéÊ¯£¨Ãô½Ý¼Ó5£©
	TriggerCondition( 1, HasItem,3915, 2000 )
	TriggerCondition( 1, HasLeaveBagGrid, 1 )
	TriggerCondition( 1, KitbagLock, 0 )
	TriggerAction( 1, TakeItem, 3915, 2000 )
	TriggerAction( 1, GiveItem, 860, 1,4 )
	TriggerFailure( 1, JumpPage, 21 )
	Text( 22, "Exchange one Gem of Wind",MultiTrigger, GetMultiTrigger(), 1) 

	InitTrigger() --3000¸ö£º65 BOSSÒÂ·þ1¼þ
	TriggerCondition( 1, HasItem,3915,3000 )
	TriggerCondition( 1, HasLeaveBagGrid, 1 )
	TriggerCondition( 1, KitbagLock, 0 )
	TriggerAction( 1, TakeItem, 3915, 3000)
	TriggerAction( 1, GiveItem, 241, 1, 4 )
	TriggerFailure( 1, JumpPage, 21 )
	Text( 22, "Exchange one Lvl65 Boss armor",MultiTrigger, GetMultiTrigger(), 1) 

	Text( 22, "Last page", JumpPage, 20 )

	Talk( 21, "Exchange failed. It seems that you have not either enough moon cakes or any blank inventory slot!" )	
end

r_talk05 = nil
function r_talk05 ()

	Talk( 1, "Donna: Hi, I am Donna. Are you a sailor? Have you been to the legendary Galley Isle? Tell me the stories if you have." )
	Text( 1, "Buy Wine", BuyPage )
	Text( 1, "Reputation Redemption",JumpPage, 5)
	--Text(1, "Royal Pirate Reputation Redemption",JumpPage,7) --

	InitTrade()
	Other(	3916	)

	Talk( 2, "Donna: Heard you have run out of Eight Treasure Wine. I have one left though. If you would like to purchase it, bring me 100000G." )
	InitTrigger()
	TriggerCondition( 1, HasMoney, 100000 )
	TriggerAction( 1, TakeMoney, 100000 )
	TriggerAction( 1, GiveItem, 4072, 1, 4 )
	TriggerFailure( 1, JumpPage, 3 )
	Text( 2, "Eight Treasures Wine", MultiTrigger,GetMultiTrigger(),1)

	Talk( 3, "Donna: It seems that you do not have enough gold. Wine is not for the poor. Come back when you have earned enough." )

	Talk(4,"Reputation is very important. Those who are extremely helpful will in turn obtain more reputation! You can redeem these reputation points for rewards here")
	Text(4,"I have faith in my reputation. I come to redeem the rewards.", JumpPage,5)

	Talk(5,"The current rewards for redemption are as follows. When you redempt your rewards, I'll minus your fame.")
	Text(5, "Endeavor Emblem", JumpPage, 8)
	Text(5, "Mini Fairy fruits", JumpPage, 9)

	InitTrigger()
	TriggerCondition( 1, HasCredit,500 )
	TriggerCondition( 1, HasLeaveBagGrid, 1 )
	TriggerCondition( 1, KitbagLock, 0 )
	TriggerAction( 1, DelRoleCredit, 500 )
	TriggerAction( 1, GiveItem, 855,5,4 )
	TriggerFailure( 1, JumpPage, 6)
	Text(5,"x5 fairy coins (500 rep)" ,MultiTrigger,GetMultiTrigger(),1)

	Talk(8,"Donna: The Endeavor Emblem is a neccessities of crafting.")
	InitTrigger()
	TriggerCondition( 1, HasCredit,20 )
	TriggerCondition( 1, HasLeaveBagGrid, 1 )
	TriggerCondition( 1, KitbagLock, 0 )
	TriggerAction( 1, DelRoleCredit, 20 )
	TriggerAction( 1, GiveItem, 2602,1,4 )
	TriggerFailure( 1, JumpPage, 6)
	Text(8,"Novice Endeavor Emblem (20 rep)" ,MultiTrigger,GetMultiTrigger(),1)

	InitTrigger()
	TriggerCondition( 1, HasCredit,200 )
	TriggerCondition( 1, HasLeaveBagGrid, 1 )
	TriggerCondition( 1, KitbagLock, 0 )
	TriggerAction( 1, DelRoleCredit, 200 )
	TriggerAction( 1, GiveItem, 2603,1,4 )
	TriggerFailure( 1, JumpPage, 6)
	Text(8,"Standard Endeavor Emblem (200 rep)" ,MultiTrigger,GetMultiTrigger(),1)

	InitTrigger()
	TriggerCondition( 1, HasCredit,2000 )
	TriggerCondition( 1, HasLeaveBagGrid, 1 )
	TriggerCondition( 1, KitbagLock, 0 )
	TriggerAction( 1, DelRoleCredit, 2000 )
	TriggerAction( 1, GiveItem, 2604,1,4 )
	TriggerFailure( 1, JumpPage, 6)
	Text(8,"Expert Endeavor Emblem (2000 rep)" ,MultiTrigger,GetMultiTrigger(),1)

	Talk(6,"Please make sure that there are empty slots in your inventory and your inventory is not binded. Either that you do not have sufficient reputation points. Help more people before you come back looking for me. Let me tell you a secret...If you are willing to accept a disciple...",CloseTalk)

	Talk(9,"Donna: Mini fruits can level your first generation fairies up to lv12. Your fame will be deducted on redemption.")
	InitTrigger()
	TriggerCondition( 1, HasCredit,2200 )
	TriggerCondition( 1, HasLeaveBagGrid, 1 )
	TriggerCondition( 1, KitbagLock, 0 )
	TriggerAction( 1, DelRoleCredit, 2200 )
	TriggerAction( 1, GiveItem, 15001,1,4 )
	TriggerFailure( 1, JumpPage, 6)
	Text(9,"mini snow dragon fruit (2200 rep)" ,MultiTrigger,GetMultiTrigger(),1)
	InitTrigger()
	TriggerCondition( 1, HasCredit,2200 )
	TriggerCondition( 1, HasLeaveBagGrid, 1 )
	TriggerCondition( 1, KitbagLock, 0 )
	TriggerAction( 1, DelRoleCredit, 2200 )
	TriggerAction( 1, GiveItem, 15002,1,4 )
	TriggerFailure( 1, JumpPage, 6)
	Text(9,"mini icespire plum (2200 rep)" ,MultiTrigger,GetMultiTrigger(),1)
	InitTrigger()
	TriggerCondition( 1, HasCredit,2200 )
	TriggerCondition( 1, HasLeaveBagGrid, 1 )
	TriggerCondition( 1, KitbagLock, 0 )
	TriggerAction( 1, DelRoleCredit, 2200 )
	TriggerAction( 1, GiveItem, 15003,1,4 )
	TriggerFailure( 1, JumpPage, 6)
	Text(9,"mini zephyr fish floss (2200 rep)" ,MultiTrigger,GetMultiTrigger(),1)
	InitTrigger()
	TriggerCondition( 1, HasCredit,2200 )
	TriggerCondition( 1, HasLeaveBagGrid, 1 )
	TriggerCondition( 1, KitbagLock, 0 )
	TriggerAction( 1, DelRoleCredit, 2200 )
	TriggerAction( 1, GiveItem, 15004,1,4 )
	TriggerFailure( 1, JumpPage, 6)
	Text(9,"mini argent mango (2200 rep)" ,MultiTrigger,GetMultiTrigger(),1)
	InitTrigger()
	TriggerCondition( 1, HasCredit,2200 )
	TriggerCondition( 1, HasLeaveBagGrid, 1 )
	TriggerCondition( 1, KitbagLock, 0 )
	TriggerAction( 1, DelRoleCredit, 2200 )
	TriggerAction( 1, GiveItem, 15005,1,4 )
	TriggerFailure( 1, JumpPage, 6)
	Text(9,"mini shaitan biscuit (2200 rep)" ,MultiTrigger,GetMultiTrigger(),1)


	--[[Talk(7,"Hi! This is the Royal Pirates! We only serve pirates with good reputation! Do you wish to redeem anything? Reputation points will be deducted upon redemption.")
	InitTrigger()
	TriggerCondition( 1, HasCredit,500 )
	TriggerCondition( 1, HasLeaveBagGrid, 1 )
	TriggerCondition( 1, KitbagLock, 0 )
	TriggerAction( 1, DelRoleCredit, 500 )
	TriggerAction( 1, GiveItem, 855,5,4 )
	TriggerAction( 1, JumpPage,8 )
	TriggerFailure( 1, JumpPage, 6)
	Text(7,"5 fairy coins: Requires 500 reputation points" ,MultiTrigger,GetMultiTrigger(),1)

	InitTrigger()
	TriggerCondition( 1, HasCredit,5000 )
	TriggerCondition( 1, HasLeaveBagGrid, 1 )
	TriggerCondition( 1, KitbagLock, 0 )
	TriggerAction( 1, DelRoleCredit, 5000 )
	TriggerAction( 1, GiveItem, 3094,3,4 )
	TriggerAction( 1, JumpPage,8 )
	TriggerFailure( 1, JumpPage, 6)
	Text(7,"Amplifier of Strive x3: Requires 5000 reputation points" ,MultiTrigger,GetMultiTrigger(),1)


	InitTrigger()
	TriggerCondition( 1, HasCredit,20000 )
	TriggerCondition( 1, HasLeaveBagGrid, 1 )
	TriggerCondition( 1, KitbagLock, 0 )
	TriggerAction( 1, DelRoleCredit, 20000 )
	TriggerAction( 1, GiveItem, 0610,1,4 )
	TriggerAction( 1, JumpPage,8 )
	TriggerFailure( 1, JumpPage, 6)
	Text(7,"1 Novice Self Destruct: Requires 20000 reputation points" ,MultiTrigger,GetMultiTrigger(),1)

	InitTrigger()
	TriggerCondition( 1, HasCredit,50000 )
	TriggerCondition( 1, HasLeaveBagGrid, 1 )
	TriggerCondition( 1, KitbagLock, 0 )
	TriggerAction( 1, DelRoleCredit, 50000 )
	TriggerAction( 1, GiveItem, 0885,1,4 )
	TriggerAction( 1, JumpPage,8 )
	TriggerFailure( 1, JumpPage, 6)
	Text(7,"Lv1 Refining Gem: Requires 50000 reputation points" ,MultiTrigger,GetMultiTrigger(),1)


	InitTrigger()
	TriggerCondition( 1, HasCredit,200000 )
	TriggerCondition( 1, HasLeaveBagGrid, 1 )
	TriggerCondition( 1, KitbagLock, 0 )
	TriggerAction( 1, DelRoleCredit, 200000 )
	TriggerAction( 1, GiveItem, 0862,1,4 )
	TriggerAction( 1, JumpPage,8 )
	TriggerFailure( 1, JumpPage, 6)
	Text(7,"Gem of Colossus x1: Requires 200000 reputation points" ,MultiTrigger,GetMultiTrigger(),1)


	InitTrigger()
	TriggerCondition( 1, HasCredit,600000 )
	TriggerCondition( 1, HasLeaveBagGrid, 1 )
	TriggerCondition( 1, KitbagLock, 0 )
	TriggerAction( 1, DelRoleCredit, 600000 )
	TriggerAction( 1, GiveItem, 1012,1,4 )
	TriggerAction( 1, JumpPage,8 )
	TriggerFailure( 1, JumpPage, 6)
	Text(7,"1 Gem of Soul: Requires 600000 reputation points" ,MultiTrigger,GetMultiTrigger(),1)

	Talk(8,"Welcome to the Royal Pirates! Work harder to achieve your aim!") ]]

	InitTrigger()
	TriggerCondition( 1, HasRecord, 255 )
	TriggerCondition( 1, NoItem, 4072, 1 )
	TriggerCondition( 1, NoRecord, 242 )
	TriggerAction( 1, JumpPage, 2 )
	TriggerFailure( 1, JumpPage, 1 )

	Start( GetMultiTrigger(), 1 )
	MisListPage(2)
	AddNpcMission ( 268 )
	AddNpcMission ( 269 )
	AddNpcMission ( 288 )
	AddNpcMission ( 502 )
	AddNpcMission ( 334 )
	AddNpcMission ( 6081 )
end 

r_talk06 = nil
function r_talk06 ()
	Talk( 1, "Little Daniel: Young adventurers should not be afraid to explore the world. Have you been to the great shrine in the desert? How about the Lone Tower in the deep Sacred forest?" )
	Text( 1, "Purchase Corals", BuyPage )
	Text (1, "Reveal Robot Cores",JumpPage,2)
	Text( 1, "I do not have time for story now.", CloseTalk)
	
	InitTrigger()
	TriggerCondition( 1, HasItem, 3933, 10 )
	TriggerCondition( 1, HasMoney, 5000 )
	TriggerAction( 1, TakeItem, 3933, 10 )
	TriggerAction( 1, TakeMoney, 5000 )
	TriggerAction( 1, GiveItem, 1812, 1, 4 )
	TriggerAction( 1, JumpPage, 3 )
	TriggerFailure( 1, JumpPage, 4 )
	Talk( 2, "Little Daniel: Oh my...I did not expect you to bring so many mechanical core. Bring me 10 Robot Core and 5000G so that I can make a Ancient Generator for you." )
	Text( 2, "Ok I will pay the (5000G) fee",  MultiTrigger, GetMultiTrigger(), 1 )
	Text( 2, "Let me consider", CloseTalk)

	Talk(3, "Little Daniel: Keep it well. This is the Ancient Generator that you will need to get inside Forsaken City. Come to me if you need more.")
	Talk(4, "Little Daniel: Sorry, you need to give me 10 Robot Cores and 5000G to make 1 Ancient Generator.")

	InitTrigger()
	TriggerCondition( 1, HasItem, 3933, 10 )
	TriggerCondition( 1, HasMoney, 5000 )
	TriggerAction( 1, JumpPage, 1 )
	TriggerFailure( 1, JumpPage, 1 )
	Start( GetMultiTrigger(), 1 )

	InitTrade()
	Weapon(	0817	)
	Weapon(	0818	)
	Weapon(	0867	)
	Weapon(	0868	)
	Weapon(	0872	)
	Weapon(	0873	)
	Weapon(	0635	)
	Weapon(	0636	)

	--AddNpcMission ( 748 )
	AddNpcMission	(1045)
	AddNpcMission	(1099)
	AddNpcMission	(1157)
	AddNpcMission	(758)
	AddNpcMission	(103)
	AddNpcMission	(191)
	AddNpcMission	(192)
	AddNpcMission	(193)
	AddNpcMission	(197)
	AddNpcMission	(1225)
	AddNpcMission	(503)
	AddNpcMission	(330)
	AddNpcMission	(331)
	AddNpcMission	(332)
	AddNpcMission	(335)
	AddNpcMission	(359)
	AddNpcMission	(360)
	AddNpcMission	(361)
	AddNpcMission	(362)
	AddNpcMission	(363)
	AddNpcMission	(364)
	AddNpcMission	(365)
	AddNpcMission	(366)
	AddNpcMission	(367)
	AddNpcMission	(368)
	AddNpcMission	(369)
	AddNpcMission	(370)
	AddNpcMission	(371)
	AddNpcMission	(522)
	AddNpcMission	(5058)
	AddNpcMission	(5062)
	MisListPage(2)
end

function r_talk04 ()
	Talk( 1, "Gina: Hello! I am Nurse Gina. Look for me if you are sick or injured!" )

	InitTrigger()
	TriggerCondition( 1, LvCheck, "<", 6 )
	TriggerCondition( 1, HasRecord, 500 )
	TriggerAction( 1, ReHp, 50 )
	TriggerCondition( 2, HasMoney, 50 )
	TriggerAction( 2, TakeMoney, 50 )
	TriggerAction( 2, ReHp,50 )
	TriggerFailure( 2, JumpPage, 3 )
	Text( 1, "Heal", MultiTrigger,GetMultiTrigger(),2)
	
	InitTrigger()
	TriggerCondition( 1, LvCheck, "<", 6 )
	TriggerCondition( 1, HasRecord, 500 )
	TriggerAction( 1, ReAll )
	TriggerCondition( 2, HasMoney, 200 )
	TriggerAction( 2, TakeMoney, 200 )
	TriggerAction( 2, ReAll )
	TriggerFailure( 2, JumpPage, 2 )
	Text( 1, "Greater Heal", MultiTrigger,GetMultiTrigger(),2)

	Talk( 2, "Gina: Sorry, healing requires 200G. You do not have enough!" )
	Talk( 3, "Gina: Sorry! Healing requires 50G. You do not have enough!" )
	Talk( 4, "I do not have any letter. I guess you got the wrong person" )
	Talk( 5, "Ya? Forget it...Thank you. Take this reward for your hard work." )

	Talk( 6, "Gina: Hello! I am Nurse Gina. Look for me if you are sick or injured!" )
	InitTrigger()
	TriggerCondition( 1, LvCheck, "<", 6 )
	TriggerCondition( 1, HasRecord, 500 )
	TriggerAction( 1, ReHp, 50 )
	TriggerCondition( 2, HasMoney, 50 )
	TriggerAction( 2, TakeMoney, 50 )
	TriggerAction( 2, ReHp,50 )
	TriggerFailure( 2, JumpPage, 3 )
	Text( 6, "Heal", MultiTrigger,GetMultiTrigger(),2)

	InitTrigger()
	TriggerCondition( 1, LvCheck, "<", 6 )
	TriggerCondition( 1, HasRecord, 500 )
	TriggerAction( 1, ReAll )
	TriggerCondition( 2, HasMoney, 200 )
	TriggerAction( 2, TakeMoney, 200 )
	TriggerAction( 2, ReAll )
	TriggerFailure( 2, JumpPage, 2 )
	Text( 6, "Greater Heal", MultiTrigger,GetMultiTrigger(),2)

	InitTrigger()
	TriggerCondition( 1, HasMission, 53 )
	TriggerCondition( 1, HasFlag, 53, 1 )
	TriggerCondition( 1, NoRecord, 53 )
	TriggerCondition( 1, NoFlag, 53, 4 )
	TriggerCondition( 1, HasItem, 2304, 1 )
	TriggerAction( 1, JumpPage, 6 )
	TriggerFailure( 1, JumpPage, 1 )

	Start( GetMultiTrigger(), 1 )
	AddNpcMission	(1048)
	AddNpcMission	(1210)
	AddNpcMission	(920)
	AddNpcMission	(921)

	MisListPage(6)
	AddNpcMission ( 6117 )
	AddNpcMission ( 6118 )
	AddNpcMission ( 6119 )
	AddNpcMission ( 6120 )
end 

function r_talk24 ()
	Talk( 1, "Dessaro: Hi, I am the highest in command in Thundoria. Do you wish to join us?" )
	InitTrigger()
	TriggerCondition( 1, HasMoney, 10000000 )
	TriggerCondition( 1, HasItem, 1780, 1 )
	TriggerCondition( 1, NoGuild )
	TriggerAction( 1, CreateGuild, 0 )
	TriggerFailure( 1, JumpPage, 2 )
	Text( 1, "Create a Navy Guild (fee: 10m)", MultiTrigger, GetMultiTrigger(), 1)

	Talk( 2, "Dessaro: To become a guild leader of the Navy Division, you will need to pay 10,000,000G and bring a Stone of Oath to prove your loyalty." )

	AddNpcMission	(566)
	AddNpcMission	(477)
	AddNpcMission	(478)
	AddNpcMission ( 6087 )
	AddNpcMission ( 6088 )
end 

function r_talk80 ()
	Talk( 1, "Mas: My family history runs as deep as Icicle Castle. Everybody here know and respected me." )
	Text( 1, "Regarding the legends of the Pirates",JumpPage, 2 )
	Text( 1, "Nothing...",CloseTalk )

	Talk( 2, "Mas: Hohoho...Pirates Crew? You wish to create one? That would have to depend on your ability." )
	InitTrigger()
	TriggerCondition( 1, HasMoney, 10000000 )
	TriggerCondition( 1, HasItem, 1780, 1 )
	TriggerAction( 1, CreateGuild, 1 )
	TriggerFailure( 1, JumpPage, 3 )
	Text( 2, "Create a Pirate Guild (fee: 10m)", MultiTrigger, GetMultiTrigger(), 1)

	Talk( 3, "Mas: To be the leader of the pirates is not an easy matter. Bring 100000G and the Stone of Oath to prove your worth" )

	AddNpcMission 	(253)
	AddNpcMission 	(254)
	AddNpcMission 	(453)
	AddNpcMission 	(698)
	AddNpcMission 	(801)
	AddNpcMission	(1004)
	AddNpcMission	(1059)
	AddNpcMission	(1114)
	AddNpcMission	(1168)
	AddNpcMission	(317)
	AddNpcMission	(321)
	AddNpcMission	(322)
	AddNpcMission	(5045)
	AddNpcMission	(5046)
	AddNpcMission	(5047)
end

-- CreateBerthEntity( "Docked", 455, 2, 217565, 284424, 0, 1, 2170, 2828, 0 )
--[[function r_talk152()
	Talk( 1, " Shirley: Hi! I am the Harbor Operator for Argent. I am in charge of all ships that is docked in this harbor. Look for me if you want to set sail." )
	InitTrigger()
	TriggerCondition( 1, HasAllBoatInBerth, 1 )
	TriggerAction( 1, LuanchBerthList, 1, 2184, 2849, 177 )
	TriggerFailure( 1, JumpPage, 3 )
	Text( 1, "Set sail", MultiTrigger, GetMultiTrigger(), 1 )
	InitTrigger()
	TriggerCondition( 1, HasLuanchOut )
	TriggerAction( 1, RepairBoat )
	TriggerCondition( 2, HasBoatInBerth, 1 )
	TriggerAction( 2, RepairBerthList, 1 )
	TriggerFailure( 2, JumpPage, 4 )
	Text( 1, "Repair Ship", MultiTrigger, GetMultiTrigger(), 2 ) 
	InitTrigger()
	TriggerCondition( 1, HasLuanchOut )
	TriggerAction( 1, SupplyBoat )
	TriggerCondition( 2, HasBoatInBerth, 1 )
	TriggerAction( 2, SupplyBerthList, 1 )
	TriggerFailure( 2, JumpPage, 5 )
	Text( 1, "Refuel", MultiTrigger, GetMultiTrigger(), 2 ) 
	InitTrigger()
	TriggerCondition( 1, HasDeadBoatInBerth, 1 )
	TriggerAction( 1, SalvageBerthList, 1 )
	TriggerFailure( 1, JumpPage, 6 )
	Text( 1, "Salvage Ship", MultiTrigger, GetMultiTrigger(), 1 ) 

	Talk( 3, "Sorry, you do not have a ship at the harbor or it was sunken. Please salvage it before setting sail again!" )
	Talk( 4, "Sorry! I only repair ships docked in this harbor. Please pay 1000G." )
	Talk( 5, "Sorry, you need to dock your ship in our harbor in order to refuel. Please pay 200G" )
	Talk( 6, "Sorry! We only salvage ships docked in our harbor. You have to pay a fee of 1000G." )
	AddNpcMission ( 289 )
	AddNpcMission ( 290 )
end]]

function r_talk53 ()
	
	
	Talk( 1, "Smithy: Hi! I have a wide variety of weapons here! Free free to browse!" )
	Text( 1, "Trade", BuyPage )
	Text( 1, "Repair", OpenRepair )
	Text( 1, "Forge", OpenForge)
	Text( 1, "Socket Milling", OpenMilling)
	--Text( 1, "Apparel Fusion", OpenFusion)
	Text( 1, "Equipment Strengthening", OpenUpgrade)
	Text( 1, "Nothing...",CloseTalk )


	InitTrade()
	Weapon(	0008	)
	Weapon(	0196	)
	Weapon(	0197	)
	Weapon(	0198	)
	Weapon(	0097	)
	Weapon(	0104	)
	Weapon(	0098	)
	Weapon(	0105	)
	Weapon(	0099	)
	Weapon(	0106	)
	Weapon(	0101	)
	Weapon(	0107	)
	Weapon(	0102	)
	Weapon(	0108	)
	Weapon(	0100	)
	Weapon(	4301	)
	Weapon(	0103	)
	Weapon(	4302	)
	Weapon(	1427	)
	Weapon(	1428	)
	Weapon(	1429	)
	Weapon(	1430	)
	Weapon(	1431	)
	Weapon(	1432	)
	Weapon(	1433	)
	Weapon(	1434	)
	Weapon(	1435	)
	Weapon(	1436	)
	Weapon(	1437	)
	Weapon(	1438	)
	Weapon(	1440	)
	Weapon(	1441	)
	Weapon(	1462	)
	Weapon(	1463	)
	Weapon(	1464	)
	Weapon(	1465	)
	Weapon(	1466	)
	Weapon(	1467	)
	Weapon(	1468	)
	Weapon(	1469	)
	Weapon(	1470	)
	Weapon(	1471	)
	Weapon(	1472	)
	Weapon(	1473	)
	Weapon(	1475	)
	Weapon(	1476	)

	AddNpcMission ( 713 )
	AddNpcMission	(1043)
	AddNpcMission	(1095)
	AddNpcMission	(1154)
	AddNpcMission	(1206)
	AddNpcMission	(91)
	AddNpcMission	(92)
	AddNpcMission	(93)

end 

function mmm_talk04 ()
	Talk( 1, "Blacksmith's apprentice: If only I have my teacher's skills." )
	Text( 1, "Regarding Item Forging", JumpPage, 2 )
	Text( 1, "Regarding Composition", JumpPage, 3 )
	Text( 1, "Regarding Socket Milling", JumpPage, 7 )
	Text( 1, "Nothing...",CloseTalk )
	
	
	Talk( 2, "Blacksmith's Disciple: To forge any item, there is a huge fee to pay. You will need to have a Refining Gem that is of equal level to that of your item as a catalyst. Then you select the type of Gems to forge onto your item. Different type of Gems have different attribute added and item type restriction. The Gems also need to be of equal level to that of your item. Do you want to forge?" )
	Text( 2, "Regarding Refining Gem", JumpPage, 4)
	Text( 2, "Regarding Gem", JumpPage, 5)
	Text( 2, "Regarding Forging Success Rate", JumpPage, 6)
	
	Talk( 3, "Blacksmith Disciple: You wish to combine something? From what I understand, you need a combining scroll and it will list the required items. Collect the items needed and talk to Grocer - Amos in Shaitan City. He is the only person who knows how to combine." )
	
	Talk( 4, "Blacksmith Disciple: Refining Gems are a crucial catalyst in the forging of items. It must match the level of the item before it can be used. High level refining gems may be obtained from combining or killing monsters." )

	Talk( 5, "Blacksmith Disciple: There are a lof of gems for forging. Fire based attack gem, water based defense gem and sacred spiritual gem. High level gems can be obtained from combining or killing monsters." )

	Talk( 6, "Blacksmith's Disciple: Success rate gets lower as item level gets higher. Max level of item that can be forged is 27. Items will disappear if forging fails." )
	
	Talk( 7, "Blacksmith Disciple: For socket milling, you need to prepare 1 Equipment Stabilizer and 1 Equipment Catalyst in order to make a socket." )

end

function dina_talk08 () 
 	Talk (1, "Weird Hat Seller: I heard that the hat refining system is now opened. It seems that I have struck gold this time. Hey, you guys, take your tume to select the perfect hat for yourselves. No hurry." ) 
 	Text (1, "Trade", BuyPage) 

	InitTrade () 
	Other (2553) 
	Other (2583) 
	Other (2584) 

 end 
 
 function x_heal01 ()
	InitTrigger()
	TriggerCondition( 1, LvCheck, "<", 6 )
	TriggerCondition( 1, HasRecord, 500 )
	TriggerAction( 1, ReAll )
	TriggerCondition( 2, HasMoney, 200 )
	TriggerAction( 2, TakeMoney, 200 )
	TriggerAction( 2, ReAll )
	TriggerFailure( 2, JumpPage, 2 )

	Talk( 1, "Eva: Hello! I am Nurse Eva of Argent Bar. Find me, when all hope is lost!" )
	Text( 1, "Greater Heal", MultiTrigger,GetMultiTrigger(),2)

	InitTrigger()
	TriggerCondition( 1, LvCheck, "<", 6 )
	TriggerCondition( 1, HasRecord, 500 )
	TriggerAction( 1, ReHp, 50 )
	TriggerCondition( 2, HasMoney, 50 )
	TriggerAction( 2, TakeMoney, 50 )
	TriggerAction( 2, ReHp,50 )
	TriggerFailure( 2, JumpPage, 3 )

	Talk( 2, "Eva: Sorry, Healing requires 200G. You do not have enough¡­" )
	Talk( 3, "Eva: Sorry! Healing requires 50G¡­You do not have enough¡­" )
end 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 