print('Loading vars.lua')

GPBN = GetPlayerByName

enumItemTypeSword = 1 -- sword
enumItemTypeGlave = 2 -- greatsword
enumItemTypeBow = 3 -- bow
enumItemTypeHarquebus = 4 -- gun
enumItemTypeFalchion = 5 -- blade
enumItemTypeMitten = 6 -- boxing glove
enumItemTypeStylet = 7 -- dagger
enumItemTypeMoneybag = 8 -- gold pouch
enumItemTypeCosh = 9 -- staff
enumItemTypeSinker = 10 -- hammer
enumItemTypeShield = 11 -- shield
enumItemTypeArrow = 12 -- arrow
enumItemTypeAmmo = 13 -- ammunition
enumItemTypeHeadpiece = 19 -- pickaxe
enumItemTypeHair = 20 -- helm
enumItemTypeFace = 21 -- face
enumItemTypeClothing = 22 -- armor
enumItemTypeGlove = 23 -- glove
enumItemTypeBoot = 24 -- shoes
enumItemTypeConch = 29 -- coral
enumItemTypeMedicine = 31 -- recovery type
enumItemTypeOvum = 32 -- addition type
enumItemTypeScroll = 36 -- scrolls
enumItemTypeGeneral = 41 -- monster drop
enumItemTypeMission = 42 -- quest items
enumItemTypeBoat = 43 -- ships
enumItemTypeWing = 44 -- wings
enumItemTypeTrade = 45
enumItemTypeBravery = 46 -- medal of valor
enumItemTypeHull = 51 -- prow
enumItemTypeEmbolon = 52 -- hull
enumItemTypeEngine = 53 -- mobility
enumItemTypeArtillery = 54 -- ship cannon
enumItemTypeAirscrew = 55 -- propeller
enumItemTypeBoatSign = 56 -- ship symbol
enumItemTypePetFodder = 57 -- fairy ration
enumItemTypePetSock = 58 -- fairy fruit
enumItemTypePet = 59 -- fairy


enumEQUIP_HEAD		= 0;
enumEQUIP_FACE		= 1;
enumEQUIP_BODY		= 2;
enumEQUIP_GLOVE		= 3;
enumEQUIP_SHOES		= 4;
enumEQUIP_NECK		= 5;
enumEQUIP_LHAND		= 6;
enumEQUIP_HAND1		= 7;
enumEQUIP_HAND2		= 8;
enumEQUIP_RHAND		= 9;
enumEQUIP_Jewelry1	= 10;
enumEQUIP_Jewelry2	= 11;
enumEQUIP_Jewelry3	= 12;
enumEQUIP_Jewelry4	= 13;
enumEQUIP_WING		= 14;
enumEQUIP_CLOAK		= 15;
enumEQUIP_FAIRY		= 16;
enumEQUIP_REAR		= 17;
enumEQUIP_MOUNT		= 18;
enumEQUIP_HEADAPP 	= 19;
enumEQUIP_FACEAPP 	= 20;
enumEQUIP_BODYAPP 	= 21;
enumEQUIP_GLOVEAPP 	= 22;
enumEQUIP_SHOESAPP 	= 23;
enumEQUIP_FAIRYAPP 	= 24;
enumEQUIP_GLOWAPP 	= 25;
enumEQUIP_DAGGERAPP = 26;
enumEQUIP_GUNAPP 	= 27;
enumEQUIP_SWORD1APP = 28;
enumEQUIP_GREATSWORDAPP = 29;
enumEQUIP_STAFFAPP	= 30;
enumEQUIP_BOWAPP 	= 31;
enumEQUIP_SWORD2APP = 32;
enumEQUIP_SHIELDAPP = 33;

enumEQUIP_MAX = 33;